### ISSUE TITLE
Add checktypes in the documentation in the chapter about 3rd party libs

### ISSUE THREAD

**Issue by smarie** [smarie/python-valid8#13]
Library [checktypes](https://pypi.python.org/pypi/checktypes) provides a way to include validation in the class definition.

```python
from valid8 import validate
from checktypes import checktype
PositiveInt = checktype('PositiveInt', int, lambda x: x > 0) x = -1 
validate('x', x, custom=PositiveInt.validate)
```
yields

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/valid8/entry_points.py", line 431, in assert_valid
    res = self.main_function(value)
  File "/usr/lib/python3.6/site-packages/checktypes/checktype.py", line 142, in validate
    raise ValueError(cls._errmsg.format(repr(val)))
ValueError: expected 'PositiveInt' but got -1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/valid8/entry_points_inline.py", line 263, in validate
    assert_valid(name, value, custom, error_type=error_type, help_msg=help_msg, **kw_context_args)
  File "/usr/lib/python3.6/site-packages/valid8/entry_points.py", line 555, in assert_valid
    none_policy=none_policy).assert_valid(name=name, value=value, **kw_context_args)
  File "/usr/lib/python3.6/site-packages/valid8/entry_points.py", line 444, in assert_valid
    help_msg=help_msg, **kw_context_args)
valid8.entry_points.ValidationError[ValueError]: Error validating [x=-1]. Validation function [validate] raised ValueError: expected 'PositiveInt' but got -1.
```

And

```python
validate('x', x, instance_of=PositiveInt)
```

yields

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/valid8/entry_points_inline.py", line 189, in validate
    assert_instance_of(value, instance_of)
  File "/usr/lib/python3.6/site-packages/valid8/entry_points_inline.py", line 34, in assert_instance_of
    raise HasWrongType(wrong_value=value, ref_type=allowed_types)
valid8.validation_lib.types.HasWrongType: Value should be an instance of <class 'checktypes.checktype.PositiveInt'>. Wrong value: [-1]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/valid8/entry_points_inline.py", line 259, in validate
    help_msg=help_msg, **kw_context_args)
  File "/usr/lib/python3.6/site-packages/valid8/entry_points_inline.py", line 93, in _create_validation_error
    raise err
valid8.entry_points.ValidationError[TypeError]: Error validating [x=-1]. HasWrongType: Value should be an instance of <class 'checktypes.checktype.PositiveInt'>. Wrong value: [-1].
```

See #14 for traceback improvements of the second example

**Comment by yahya-abou-imran** [comment]
```
Validation function [validate] raised ValueError:
```

It should be `[PositiveInt.validate]`. You could try to use __qualname__ instead of __name__ to show the name of the function.

**Comment by smarie** [comment]
Current implementation of name is

```python
def get_callable_name(validation_callable: Callable) -> str:
    """
    Used internally to get the name to display concerning a validation function, in error messages for example.
    :param validation_callable: a callable
    :return:
    """
return validation_callable.__name__ if hasattr(validation_callable, '__name__') else str(validation_callable)
```

I'm wondering if checking for `qualname` first would be transparent or would make many functions look ugly... I have to make some tests here.

**Comment by smarie** [comment]
I tried today to do this and the latest version of checktypes does not install.

See [#1](https://gitlab.com/yahya-abou-imran/checktypes/issues/1)
